version: '3.8'

services:
  hermes-broker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hermes-broker
    image: ghcr.io/choedaelyeon/stock-trader:latest
    ports:
      - "8080:8080"
    # 절대 경로를 사용하시거나, docker-compose.yml과 같은 폴더에 있다면 아래처럼 상대 경로(.env)를 사용하셔도 무방합니다.
    env_file:
      - /home/chleofus6272000/app/stock-broker/.env
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
