package com.hermes.broker.trading.domain.risk;

public enum RiskDecision {
    ALLOWED,
    BLOCKED_BY_KILL_SWITCH,
    BLOCKED_BY_DAILY_LOSS,
    BLOCKED_BY_MAX_ORDER_AMOUNT,
    BLOCKED_BY_MAX_DAILY_TRADES,
    BLOCKED_BY_MAX_POSITION_COUNT,
    BLOCKED_BY_STOCK_EXPOSURE,
    BLOCKED_BY_SECTOR_EXPOSURE,
    BLOCKED_BY_DUPLICATE_ORDER,
    BLOCKED_BY_INSUFFICIENT_BALANCE,
    BLOCKED_BY_INVALID_QUANTITY,
    BLOCKED_BY_AVERAGING_DOWN
}
